# Generated by Django 3.2.6 on 2021-09-01 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210827_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 13, 21, 52, 986437)),
        ),
    ]
