# Generated by Django 3.2.6 on 2021-09-01 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='previous_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 13, 25, 58, 924619)),
        ),
    ]
