# Generated by Django 3.2.6 on 2021-09-03 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210901_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 12, 7, 13, 119561)),
        ),
    ]
