# Generated by Django 3.2.6 on 2021-09-04 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210904_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 13, 38, 11, 946745)),
        ),
    ]
